In [1]:
import sys

print(sys.executable)

/home/prashant/Projects/credit-risk-project/.venv/bin/python


In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)

3.0.5


In [7]:
file_path = "../data/raw/default of credit card clients.xls"

df = pd.read_excel(file_path,header = 1)

df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0


In [8]:
print(f"Shape: {df.shape}")

Shape: (30000, 25)


In [9]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].unique()[:20])


--- ID ---
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

--- LIMIT_BAL ---
[ 20000 120000  90000  50000 500000 100000 140000 200000 260000 630000
  70000 250000 320000 360000 180000 130000 450000  60000 230000 160000]

--- SEX ---
[2 1]

--- EDUCATION ---
[2 1 3 5 4 6 0]

--- MARRIAGE ---
[1 2 3 0]

--- AGE ---
[24 26 34 37 57 29 23 28 35 51 41 30 49 39 40 27 47 33 32 54]

--- PAY_0 ---
[ 2 -1  0 -2  1  3  4  8  7  5  6]

--- PAY_2 ---
[ 2  0 -1 -2  3  5  7  4  1  6  8]

--- PAY_3 ---
[-1  0  2 -2  3  4  6  7  1  5  8]

--- PAY_4 ---
[-1  0 -2  2  3  4  5  7  6  1  8]

--- PAY_5 ---
[-2  0 -1  2  3  5  4  7  8  6]

--- PAY_6 ---
[-2  2  0 -1  3  6  4  7  8  5]

--- BILL_AMT1 ---
[  3913   2682  29239  46990   8617  64400 367965  11876  11285      0
  11073  12261  12137  65802  70887  50614  15376 253286  38358    316]

--- BILL_AMT2 ---
[  3102   1725  14027  48233   5670  57069 412023    380  14096      0
   9787  21670   6500  67369  67060  29173  18010 246536  276

Investigate the Age

In [10]:
df["AGE"].describe()

count    30000.000000
mean        35.485500
std          9.217904
min         21.000000
25%         28.000000
50%         34.000000
75%         41.000000
max         79.000000
Name: AGE, dtype: float64

In [11]:
df["AGE"].sort_values().head(20).tolist()

[21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21]

In [12]:
df["AGE"].sort_values(ascending=False).head(20).tolist()

[79,
 75,
 75,
 75,
 74,
 73,
 73,
 73,
 73,
 72,
 72,
 72,
 71,
 71,
 71,
 70,
 70,
 70,
 70,
 70]

Investigate Education