In [1]:
import sys

print(sys.executable)

/home/prashant/Projects/credit-risk-project/.venv/bin/python


In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)

3.0.5


In [3]:
file_path = "../data/raw/default of credit card clients.xls"

df = pd.read_excel(file_path,header = 1)

df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0


In [4]:
print(f"Shape: {df.shape}")

Shape: (30000, 25)


In [5]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].unique()[:20])


--- ID ---
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

--- LIMIT_BAL ---
[ 20000 120000  90000  50000 500000 100000 140000 200000 260000 630000
  70000 250000 320000 360000 180000 130000 450000  60000 230000 160000]

--- SEX ---
[2 1]

--- EDUCATION ---
[2 1 3 5 4 6 0]

--- MARRIAGE ---
[1 2 3 0]

--- AGE ---
[24 26 34 37 57 29 23 28 35 51 41 30 49 39 40 27 47 33 32 54]

--- PAY_0 ---
[ 2 -1  0 -2  1  3  4  8  7  5  6]

--- PAY_2 ---
[ 2  0 -1 -2  3  5  7  4  1  6  8]

--- PAY_3 ---
[-1  0  2 -2  3  4  6  7  1  5  8]

--- PAY_4 ---
[-1  0 -2  2  3  4  5  7  6  1  8]

--- PAY_5 ---
[-2  0 -1  2  3  5  4  7  8  6]

--- PAY_6 ---
[-2  2  0 -1  3  6  4  7  8  5]

--- BILL_AMT1 ---
[  3913   2682  29239  46990   8617  64400 367965  11876  11285      0
  11073  12261  12137  65802  70887  50614  15376 253286  38358    316]

--- BILL_AMT2 ---
[  3102   1725  14027  48233   5670  57069 412023    380  14096      0
   9787  21670   6500  67369  67060  29173  18010 246536  276

Investigate the Age

In [6]:
df["AGE"].describe()

count    30000.000000
mean        35.485500
std          9.217904
min         21.000000
25%         28.000000
50%         34.000000
75%         41.000000
max         79.000000
Name: AGE, dtype: float64

In [7]:
df["AGE"].sort_values().head(20).tolist()

[21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21]

In [8]:
df["AGE"].sort_values(ascending=False).head(20).tolist()

[79,
 75,
 75,
 75,
 74,
 73,
 73,
 73,
 73,
 72,
 72,
 72,
 71,
 71,
 71,
 70,
 70,
 70,
 70,
 70]

Investigate Education

In [9]:
df["EDUCATION"].value_counts().sort_index()

EDUCATION
0       14
1    10585
2    14030
3     4917
4      123
5      280
6       51
Name: count, dtype: int64

In [10]:
df["MARRIAGE"].value_counts().sort_index()

MARRIAGE
0       54
1    13659
2    15964
3      323
Name: count, dtype: int64

In [11]:
payment_cols = [
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

for col in payment_cols:
    print(f"\n{col}")
    print(df[col].value_counts().sort_index())


PAY_0
PAY_0
-2     2759
-1     5686
 0    14737
 1     3688
 2     2667
 3      322
 4       76
 5       26
 6       11
 7        9
 8       19
Name: count, dtype: int64

PAY_2
PAY_2
-2     3782
-1     6050
 0    15730
 1       28
 2     3927
 3      326
 4       99
 5       25
 6       12
 7       20
 8        1
Name: count, dtype: int64

PAY_3
PAY_3
-2     4085
-1     5938
 0    15764
 1        4
 2     3819
 3      240
 4       76
 5       21
 6       23
 7       27
 8        3
Name: count, dtype: int64

PAY_4
PAY_4
-2     4348
-1     5687
 0    16455
 1        2
 2     3159
 3      180
 4       69
 5       35
 6        5
 7       58
 8        2
Name: count, dtype: int64

PAY_5
PAY_5
-2     4546
-1     5539
 0    16947
 2     2626
 3      178
 4       84
 5       17
 6        4
 7       58
 8        1
Name: count, dtype: int64

PAY_6
PAY_6
-2     4895
-1     5740
 0    16286
 2     2766
 3      184
 4       49
 5       13
 6       19
 7       46
 8        2
Name: count, dtype: int6

In [12]:
df["LIMIT_BAL"].describe()

count      30000.000000
mean      167484.322667
std       129747.661567
min        10000.000000
25%        50000.000000
50%       140000.000000
75%       240000.000000
max      1000000.000000
Name: LIMIT_BAL, dtype: float64

In [13]:
df["LIMIT_BAL"].sort_values().head(10).tolist()

[10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]

In [15]:
df["LIMIT_BAL"].sort_values(ascending=False).head(10).tolist()

[1000000,
 800000,
 800000,
 780000,
 780000,
 760000,
 750000,
 750000,
 750000,
 750000]

In [16]:
bill_cols = [
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3",
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6"
]

df[bill_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
BILL_AMT1,30000.0,51223.330900,73635.860576,-165580.0,3558.75,22381.5,67091.00,964511.0
BILL_AMT2,30000.0,49179.075167,71173.768783,-69777.0,2984.75,21200.0,64006.25,983931.0
BILL_AMT3,30000.0,47013.154800,69349.387427,-157264.0,2666.25,20088.5,60164.75,1664089.0
BILL_AMT4,30000.0,43262.948967,64332.856134,-170000.0,2326.75,19052.0,54506.00,891586.0
BILL_AMT5,30000.0,40311.400967,60797.155770,-81334.0,1763.00,18104.5,50190.50,927171.0
BILL_AMT6,30000.0,38871.760400,59554.107537,-339603.0,1256.00,17071.0,49198.25,961664.0


In [17]:
pay_amt_cols = [
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3",
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6"
]

df[pay_amt_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
PAY_AMT1,30000.0,5663.580500,16563.280354,0.0,1000.00,2100.0,5006.00,873552.0
PAY_AMT2,30000.0,5921.163500,23040.870402,0.0,833.00,2009.0,5000.00,1684259.0
PAY_AMT3,30000.0,5225.681500,17606.961470,0.0,390.00,1800.0,4505.00,896040.0
PAY_AMT4,30000.0,4826.076867,15666.159744,0.0,296.00,1500.0,4013.25,621000.0
PAY_AMT5,30000.0,4799.387633,15278.305679,0.0,252.50,1500.0,4031.50,426529.0
PAY_AMT6,30000.0,5215.502567,17777.465775,0.0,117.75,1500.0,4000.00,528666.0


In [18]:
print("Rows:", len(df))
print("Unique IDs:", df["ID"].nunique())
print("Duplicate IDs:", df["ID"].duplicated().sum())

Rows: 30000
Unique IDs: 30000
Duplicate IDs: 0


In [19]:
quality_report = pd.DataFrame({
    "dtype": df.dtypes,
    "missing_count": df.isna().sum(),
    "missing_pct": df.isna().mean() * 100,
    "unique_values": df.nunique()
})

quality_report

,dtype,missing_count,missing_pct,unique_values
ID,int64,0,0.0,30000
LIMIT_BAL,int64,0,0.0,81
SEX,int64,0,0.0,2
EDUCATION,int64,0,0.0,7
MARRIAGE,int64,0,0.0,4
AGE,int64,0,0.0,56
PAY_0,int64,0,0.0,11
PAY_2,int64,0,0.0,11
PAY_3,int64,0,0.0,11
PAY_4,int64,0,0.0,11


In [20]:
quality_report.sort_values(
    "unique_values",
    ascending=True
)

,dtype,missing_count,missing_pct,unique_values
SEX,int64,0,0.0,2
default payment next month,int64,0,0.0,2
MARRIAGE,int64,0,0.0,4
EDUCATION,int64,0,0.0,7
PAY_5,int64,0,0.0,10
PAY_6,int64,0,0.0,10
PAY_2,int64,0,0.0,11
PAY_4,int64,0,0.0,11
PAY_3,int64,0,0.0,11
PAY_0,int64,0,0.0,11


In [21]:
df["AGE"].describe()

df["EDUCATION"].value_counts().sort_index()

df["MARRIAGE"].value_counts().sort_index()

for col in payment_cols:
    print(f"\n{col}")
    print(df[col].value_counts().sort_index())

quality_report


PAY_0
PAY_0
-2     2759
-1     5686
 0    14737
 1     3688
 2     2667
 3      322
 4       76
 5       26
 6       11
 7        9
 8       19
Name: count, dtype: int64

PAY_2
PAY_2
-2     3782
-1     6050
 0    15730
 1       28
 2     3927
 3      326
 4       99
 5       25
 6       12
 7       20
 8        1
Name: count, dtype: int64

PAY_3
PAY_3
-2     4085
-1     5938
 0    15764
 1        4
 2     3819
 3      240
 4       76
 5       21
 6       23
 7       27
 8        3
Name: count, dtype: int64

PAY_4
PAY_4
-2     4348
-1     5687
 0    16455
 1        2
 2     3159
 3      180
 4       69
 5       35
 6        5
 7       58
 8        2
Name: count, dtype: int64

PAY_5
PAY_5
-2     4546
-1     5539
 0    16947
 2     2626
 3      178
 4       84
 5       17
 6        4
 7       58
 8        1
Name: count, dtype: int64

PAY_6
PAY_6
-2     4895
-1     5740
 0    16286
 2     2766
 3      184
 4       49
 5       13
 6       19
 7       46
 8        2
Name: count, dtype: int6

,dtype,missing_count,missing_pct,unique_values
ID,int64,0,0.0,30000
LIMIT_BAL,int64,0,0.0,81
SEX,int64,0,0.0,2
EDUCATION,int64,0,0.0,7
MARRIAGE,int64,0,0.0,4
AGE,int64,0,0.0,56
PAY_0,int64,0,0.0,11
PAY_2,int64,0,0.0,11
PAY_3,int64,0,0.0,11
PAY_4,int64,0,0.0,11
